select * from all_tables;
DROP TABLE MEMBER;
DROP TABLE BOARD;

SELECT * FROM BOARD;
SELECT * FROM CLIENT;


CREATE TABLE BOARD(
	NUM INT PRIMARY KEY,		-- 게시글  고유번호
	TITLE VARCHAR(20),			-- 제목
	CID VARCHAR(10),			-- 작성자 아이디
	CONTENT VARCHAR(100),		-- 내용
	BDATE DATE DEFAULT SYSDATE	-- 작성일
);
INSERT INTO BOARD VALUES (1,'첫번째 게시글','jin','this is first post!',SYSDATE);
SELECT * FROM BOARD WHERE TITLE LIKE '%게%';

CREATE TABLE CLIENT(
	CID VARCHAR(10) PRIMARY KEY,	-- 회원 고유 아이디
	CNAME VARCHAR(15),				-- 이름
	PASSWORD VARCHAR(10),			-- 패스워드
	ROLE VARCHAR(10) DEFAULT 'USER' -- '유저' OR '관리자'
);
INSERT INTO CLIENT VALUES ('admin','관리자','1212','ADMIN');
INSERT INTO CLIENT VALUES ('qwe','큐','1212','USER');
SELECT * FROM CLIENT WHERE CID='qwe' AND PASSWORD='1212';
